# Fichier de configuration Nginx pour le conteneur frontend

server {
    listen 80;

    server_name localhost;

    # Définition du résolveur DNS de Docker.
    # Ceci est essentiel pour la résolution de noms de services.
    resolver 127.0.0.11 valid=30s;

    # Déclaration d'une variable qui contiendra l'adresse de l'API Gateway.
    # L'utilisation d'une variable retarde la résolution DNS jusqu'à ce qu'une requête arrive.
    set $api_gateway_service "exam-api-gateway-service:8090";

    # Configuration pour servir l'application Angular
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy pour les requêtes API
    location /api/ {
        # proxy_pass utilise la variable, ce qui déclenche la résolution DNS dynamique
        proxy_pass http://$api_gateway_service;

        # Réécriture de l'URL pour retirer le préfixe /api/
        rewrite ^/api/(.*)$ /$1 break;

        # Configuration des en-têtes de la requête
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
