server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # 🔁 Frontend SPA Angular
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 📡 Reverse proxy vers Gateway pour les APIs
    location /students/ {
        proxy_pass http://api-gateway-service:8090/students/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
    }

    location /courses/ {
        proxy_pass http://api-gateway-service:8090/courses/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
    }

    location /answers/ {
        proxy_pass http://api-gateway-service:8090/answers/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
    }

    location /exams/ {
        proxy_pass http://api-gateway-service:8090/exams/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
    }

    location /users/ {
        proxy_pass http://api-gateway-service:8090/users/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
    }

    # 🔍 Pour Eureka ou Actuator si utile en admin
    location /eureka/ {
        proxy_pass http://api-gateway-service:8090/eureka/;
    }
}