apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-exam-pvc
  namespace: exam-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path # CHANGÉ DE 'local-storage' À 'local-path'
