apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-exam-pv
  # ATTENTION : La ligne 'namespace: exam-namespace' a été retirée car les PVs sont des ressources globales.
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path # CHANGÉ DE 'local-storage' À 'local-path'
  local:
    path: /mnt/mysql-exam-data # Assurez-vous que ce chemin existe sur le nœud 'cd-vm'
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - cd-vm
