apiVersion: v1
kind: Service
metadata:
  name: exam-service
  namespace: exam-namespace
spec:
  selector:
    app: exam-service
  ports:
  - port: 8082
    targetPort: 8082
  type: ClusterIP
