# k8s/exam-service/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: exam-service # Ce nom sera utilisé par l'API Gateway pour router les requêtes
  labels:
    app: exam-service
spec:
  selector:
    app: exam-service # Sélectionne les pods de votre déploiement exam-service
  ports:
    - protocol: TCP
      port: 8082 # Port sur lequel le service sera exposé à l'intérieur du cluster
      targetPort: 8082 # Port du conteneur exam-service
  type: ClusterIP # Accès interne au cluster uniquement
