apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: exam-project-ingress
  annotations:
    # SUPPRIMEZ ou COMMENTEZ cette annotation.
    # L'Ingress doit passer le chemin complet à l'API Gateway.
    # nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: exam.local # <-- AJOUTEZ CETTE LIGNE
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-gateway-service
                port:
                  number: 8090
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
