# k8s/user-service/postgres-user-db-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-user-db # Nom de votre déploiement PostgreSQL
  labels:
    app: postgres-user-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-user-db
  template:
    metadata:
      labels:
        app: postgres-user-db
    spec:
      containers:
      - name: postgres-user-db
        image: postgres:13 # L'image Docker de PostgreSQL. Vérifiez si c'est la version que vous utilisez.
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432 # Port par défaut de PostgreSQL
        env: # Variables d'environnement pour configurer PostgreSQL
        - name: POSTGRES_DB # Nom de la base de données par défaut à créer
          value: "userdb" # Le nom de la DB que votre user-service va utiliser
        - name: POSTGRES_USER # Nom de l'utilisateur
          value: "userdbuser"
        - name: POSTGRES_PASSWORD # Mot de passe de l'utilisateur
          value: "userdbpass" # <-- ATTENTION: Valeur en clair. Pour la production, utilisez des Secrets Kubernetes!
        volumeMounts:
        - name: postgres-user-storage
          mountPath: /var/lib/postgresql/data # Chemin où PostgreSQL stocke ses données
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "600m"
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          exec:
            command: ["pg_isready", "-h", "localhost", "-p", "5432", "-U", "userdbuser"] # Vérifie la connexion à PostgreSQL
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: postgres-user-storage
        persistentVolumeClaim:
          claimName: postgres-user-data-pvc # Référence à la PVC créée ci-dessus
