apiVersion: v1
kind: Service
metadata:
  name: postgres-user-db
  namespace: exam-namespace
spec:
  selector:
    app: postgres-user-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP