apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-gateway-service
    spec:
      containers:
      - name: api-gateway
        image: johankarl/exam-api-gateway-service
        ports:
        - containerPort: 8090
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-service:8761/eureka"
        - name: JAVA_OPTS
          value: "-Xmx1024m -Xms512m" # Augmentation de la mémoire JVM
        resources:
          requests:
            memory: "1024Mi" # Demande d'au moins 1 GB de mémoire
            cpu: "750m"     # Demande d'au moins 0.75 CPU core
          limits:
            memory: "1536Mi" # Limite à 1.5 GB de mémoire
            cpu: "1500m"     # Limite à 1.5 CPU core
        livenessProbe:
          tcpSocket:       # Changé en tcpSocket
            port: 8090
          initialDelaySeconds: 120 # Délai initial augmenté à 2 minutes
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:    # Ajouté et changé en tcpSocket
          tcpSocket:
            port: 8090
          initialDelaySeconds: 90 # Délai initial augmenté à 1.5 minutes
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
