server:
  address: 0.0.0.0
  port: 8761

spring:
  application:
    name: eureka-service

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

  server:
    enableSelfPreservation: false
    waitTimeInMsWhenSyncEmpty: 0
    evictionIntervalTimerInMs: 60000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
