apiVersion: apps/v1
kind: Deployment
metadata:
  name: answer-service
  labels:
    app: answer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: answer-service
  template:
    metadata:
      labels:
        app: answer-service
    spec:
      containers:
        - name: answer-service
          image: johankarl/exam-answer-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-service:8761/eureka
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongo-answer-db:27017/answerdb
            - name: JAVA_OPTS
              value: "-Xmx512m -Xms256m"
          resources:
            requests:
              memory: "512Mi"
              cpu: "300m"
            limits:
              memory: "1Gi"
              cpu: "600m"
