apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-answer-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongo-answer
  persistentVolumeReclaimPolicy: Retain
