apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-answer-db
  namespace: exam-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-answer-db
  template:
    metadata:
      labels:
        app: mongo-answer-db
    spec:
      containers:
        - name: mongo
          image: mongo:5.0
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
          livenessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.runCommand({ ping: 1 })"
            initialDelaySeconds: 120 # Augmenté pour donner plus de temps au démarrage de MongoDB
            periodSeconds: 20       # Vérifie moins fréquemment
            timeoutSeconds: 10      # Augmenté pour donner plus de temps à la commande mongo
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.runCommand({ ping: 1 })"
            initialDelaySeconds: 90 # Augmenté pour s'assurer que MongoDB est vraiment prêt
            periodSeconds: 10       # Vérifie moins fréquemment
            timeoutSeconds: 10      # Augmenté
            failureThreshold: 3
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-answer-pvc
