apiVersion: v1
kind: Service
metadata:
  name: mongo-answer-db
  namespace: exam-namespace
spec:
  selector:
    app: mongo-answer-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
