apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service
  namespace: exam-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
    spec:
      containers:
        - name: course-service
          image: johankarl/exam-course-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-exam-db:3306/examdb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-service:8761/eureka"
            - name: JAVA_OPTS
              value: "-Xmx512m -Xms256m"
          livenessProbe:
            tcpSocket: # Changé de httpGet à tcpSocket
              port: 8081
            initialDelaySeconds: 90 # Augmenté
            periodSeconds: 15       # Augmenté
            timeoutSeconds: 5       # Augmenté
            failureThreshold: 3
          readinessProbe:
            tcpSocket: # Changé de httpGet à tcpSocket
              port: 8081
            initialDelaySeconds: 60 # Augmenté
            periodSeconds: 10       # Augmenté
            timeoutSeconds: 5       # Augmenté
            failureThreshold: 3
