apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-service
  template:
    metadata:
      labels:
        app: eureka-service
    spec:
      containers:
      - name: eureka
        image: johankarl/exam-eureka-service:latest # Image from Docker Hub with ':latest' tag
        ports:
        - containerPort: 8761
        env:
        - name: JAVA_OPTS
          value: "-Xmx512m -Xms256m"
        resources:
          limits:
            memory: "1Gi"
            cpu: "800m"
