apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  namespace: exam-namespace
spec:
  selector:
    app: eureka-service # MODIFIÉ : Pour correspondre au nouveau label du déploiement
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: ClusterIP
