# k8s/sonarqube/sonar-db-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: sonar-db # C'est le nom que SonarQube utilisera pour se connecter
  labels:
    app: sonar-db
spec:
  selector:
    app: sonar-db # Sélectionne les pods de votre déploiement PostgreSQL pour SonarQube
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP # Accès interne au cluster uniquement
