# k8s/sonarqube/sonar-db-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-db-data-pvc # Nom unique pour votre volume persistant SonarQube DB
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi # Demande 2 Gigaoctets de stockage. Ajustez si nécessaire.
