# k8s/zap/zap-automation-plan.yaml - RECOMMANDÉ (basé sur l'IP Minikube)
env:
  contexts:
    - excludePaths: []
      name: baseline
      urls:
        - http://192.168.49.2/ # Pour le frontend via Ingress
        - http://192.168.49.2/api/ # Pour l'API Gateway via Ingress
  parameters:
    failOnError: true
    progressToStdout: false
  proxy:
jobs:
  - parameters:
      enableTags: false
      maxAlertsPerRule: 10
    type: passiveScan-config
  - parameters:
      maxDuration: 1
      # Ciblez l'Ingress pour le spider aussi
      url: http://192.168.49.2/ # Ou http://192.168.49.2/api/ si vous voulez cibler spécifiquement l'API
    type: spider
  - parameters:
      maxDuration: 0
    type: passiveScan-wait
  - parameters:
      format: Long
      summaryFile: /zap/wrk/zap_out.json
    rules: []
    type: outputSummary
  - parameters:
      reportDescription: ''
      reportDir: /zap/wrk/
      reportFile: zap_report.json
      reportTitle: ZAP Scanning Report
      template: traditional-json
    type: report
