apiVersion: v1
kind: ConfigMap
metadata:
  name: zap-automation-plan
  namespace: exam-namespace
data:
  zap-plan.yaml: |
    context:
      name: exam-context
      urls:
      - http://exam.local/
      - http://exam.local/api
      - http://exam.local/answer-service
      - http://exam.local/exam-service
      - http://exam.local/course-service
      - http://exam.local/user-service
    spider:
      maxDepth: 5
    activeScan:
      policy: Default Policy
