apiVersion: batch/v1
kind: Job
metadata:
  name: owasp-zap-automation-${BUILD_NUMBER}
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: zap
        image: owasp/zap2docker-stable
        command:
        - zap.sh
        - -cmd
        - -autorun
        - /zap/wrk/zap-plan.yaml
        volumeMounts:
        - name: zap-plan
          mountPath: /zap/wrk/zap-plan.yaml
          subPath: zap-plan.yaml
        - name: zap-report
          mountPath: /zap/wrk
      volumes:
      - name: zap-plan
        configMap:
          name: zap-automation-plan
      - name: zap-report
        emptyDir: {}
      restartPolicy: Never
