apiVersion: v1
kind: ConfigMap
metadata:
  name: zap-automation-plan-config
  namespace: default
data:
  zap-automation-plan.yaml: |
    env:
      contexts:
        - excludePaths: []
          name: baseline
          urls:
            - http://frontend:80/
            - http://api-gateway-service:8090/
      parameters:
        failOnError: false # Désactivé pour débogage
        progressToStdout: true # Activer les logs détaillés
      proxy:
    jobs:
      - parameters:
          enableTags: false
          maxAlertsPerRule: 10
        type: passiveScan-config
      - parameters:
          maxDuration: 5
          url: http://frontend:80/
        type: spider
      - parameters:
          maxDuration: 0
        type: passiveScan-wait
      - parameters:
          format: Long
          summaryFile: /zap/wrk/zap_out.json
        rules: []
        type: outputSummary
      - parameters:
          reportDescription: 'Rapport de Scan de Sécurité ZAP'
          reportDir: /zap/wrk/
          reportFile: zap_report.json
          reportTitle: 'Rapport de Scan de Sécurité ZAP'
          template: traditional-json
        type: report
