# k8s/zap/zap-automation-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: owasp-zap-automation-{{ .Release.Name }}
spec:
  template:
    metadata:
      labels:
        app: owasp-zap-automation
    spec:
      containers:
      - name: zap-automation
        # La balise de l'image a été changée de ':stable' à ':latest'
        image: zaproxy/zap-stable:latest # Utilisez "latest" comme balise
        command: ["zap.sh", "-cmd", "-autorun", "/zap/zap-automation-plan.yaml"]
        volumeMounts:
        - name: zap-plan-volume
          mountPath: /zap/zap-automation-plan.yaml
          subPath: zap-automation-plan.yaml
        - name: zap-work-volume
          mountPath: /zap/wrk
      restartPolicy: Never
      volumes:
      - name: zap-plan-volume
        configMap:
          name: zap-automation-plan-config
      - name: zap-work-volume
        emptyDir: {}
